#!/bin/sh

# Enable the use of the HTTP_DOMAIN envirnmental variable
if [ -z "$HTTP_DOMAIN" ]; then
	DOMAIN="domain"
else
	DOMAIN="$HTTP_DOMAIN"
fi

# Make sure the required directory structure exists.
if ! [ -d /var/www/$DOMAIN/public ]; then
	mkdir -p /var/www/$DOMAIN/public
fi
if ! [ -d /var/www/$DOMAIN/log ]; then
	mkdir /var/www/$DOMAIN/log
fi

# Adjust the site template configuration to match the domain.
sed -e "s/DOMAIN/$DOMAIN/g" </etc/hiawatha/site.conf >/tmp/site.conf
cp /tmp/site.conf /etc/hiawatha/site.conf

# Read TLS environmental variable
if [ -n "$HTTP_REQUIRE_TLS" ]; then
	sed -e "s/.*RequireTLS.*/    RequireTLS = $HTTP_REQUIRE_TLS/" </etc/hiawatha/site.conf >/tmp/site.conf
	cp /tmp/site.conf /etc/hiawatha/site.conf
fi

# Adjust certificates generated by Lets Encrypt to a format readable by hiawatha.
cd /certs
if [ -e key.pem ] && [ -e cert.pem ] && [ -e chain.pem ]; then
	cp key.pem hiawatha.pem
	echo >>hiawatha.pem
	cat cert.pem >>hiawatha.pem
	echo >>hiawatha.pem
	cat chain.pem >>hiawatha.pem
fi

# Run hiawatha in the foreground.
/usr/sbin/hiawatha -d -c /etc/hiawatha
